### ISSUE TITLE
Description on how to run either locally or for own discord 

### ISSUE THREAD

**Issue by TheYoBots** [michael1241/discotron#4]
Hi, Could a README.md file be made for this repository with details as to how it can be used and what features it has?

Thank you!

**Comment by michael1241** [comment]
Unlikely, I don't know how to set it up on a server :smile: I had help.

Here's the discotron.ini file:
```
[uwsgi]
#http-socket = localhost:9090
socket = localhost:9090
master = true
wsgi-file = /home/discotron/discotron/discotron.py
callable = app
virtualenv = ./venv/
```

and here's the discotron.service file, it's running as a systemd service:
```
[Unit]
Description=Discotron Discord-Patron Bot
After=network.target

[Service]
User=discotron
Group=discotron
WorkingDirectory=/home/discotron/discotron/
ExecStart=/home/discotron/discotron/venv/bin/uwsgi --plugins python3 --ini discotron.ini
PrivateTmp=true
PrivateDevices=true
DevicePolicy=closed
ProtectSystem=full
CapabilityBoundingSet=
NoNewPrivileges=true
Restart=always

[Install]
WantedBy=multi-user.target
```
I'm not going to write a full readme though sorry, best of luck setting it up if you can though. As far as features, it just uses oauth to verify a discord and a Lichess account, then applies the "patron" role to the discord user if they have patron on Lichess.

**Comment by TheYoBots** [comment]
Thanks for the explanation!
